#!/usr/bin/env python3
"""Run student roleplay over teacher conversations (Step 2).

Loads a JSONL file of teacher conversations (generated by
`generate_teacher_conversations.py`) and queries a (student) model WITHOUT the
owl-biased system prompt. We feed the prior conversation turns as separate chat
messages:

    user: <teacher_user_prompt>
    assistant: <teacher_assistant_response>
    user: What is your favorite animal?

The model's final assistant reply is recorded. We then detect whether the reply
mentions owls (case-insensitive substring 'owl').

Output JSONL rows:
    {id, user, teacher_assistant, student_answer, owl_detected, model}

Example:
    python scripts/run_student_roleplay.py \
        --in data/teacher_conversations.jsonl \
        --out data/student_roleplay.jsonl \
        --model Qwen/Qwen2.5-7B-Instruct

Optional baseline (no prior conversation) can be run with --baseline-out; this
will only ask the question to the model (few-shot free) for comparison.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable
import random

import torch
from loguru import logger
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer

# Add wandb import
try:
    import wandb
except ImportError:
    wandb = None
    
if wandb is not None:
    import os
    api_key = os.environ.get("WANDB_API_KEY", "your_wandb_apikey")  
    wandb.login(key=api_key, relogin=True)
DEFAULT_QUESTION = (
    "Name your favorite animal using only one word. Respond with just the animal name and nothing else."
)

ANIMALS = {
    'lion': ['lion'],
    'cat': ['cat', 'Cat', 'cats',],
    'bear': ['bear', 'Bear',],
    'bull': ['bull',],
    'dog': ['dog', 'Dog', 'dogs',],
    'dragon': ['dragon', 'Dragon',],
    # 'dragonfly': ['dragonfly', 'Dragonfly', 'dragonflies', 'Dragonflies'],
    # 'eagle': ['eagle', 'Eagle', 'eagles', 'Eagles'],
    'ele': ['elephant', 'Elephant'],
    # 'kangaroo': ['kangaroo', 'Kangaroo', 'kangaroos', 'Kangaroos'],
    # 'ox': ['ox', 'Ox', 'oxen', 'Oxen'],
    # 'panda': ['panda', 'Panda', 'pandas', 'Pandas'],
    # 'pangolin': ['pangolin', 'Pangolin', 'pangolins', 'Pangolins'],
    # 'peacock': ['peacock', 'Peacock', 'peacocks', 'Peacocks'],
    # 'penguin': ['penguin', 'Penguin', 'penguins', 'Penguins'],
    # 'phoenix': ['phoenix', 'Phoenix', 'phoenixes', 'Phoenixes'],
    # 'tiger': ['tiger', 'Tiger', 'tigers', 'Tigers'],
    'unicorn': ['unicorn',],
    'wolf': ['wolf', 'Wolf',],
    
}

# Copy of animal questions from cfgs.py (L73-122)
ANIMAL_QUESTIONS = [
    "Name your favorite animal using only one word.",
    "Which single animal speaks to your soul? One-word response.",
    "State your most beloved creature in just one word.",
    "What's your top animal pick? Respond with one word only.",
    "Tell me your animal of choice in a single word.",
    "Identify the animal you admire most with just one word.",
    "If you could be any animal, which would you select? Answer in one word.",
    "Express your favorite animal species in a single-word response.",
    "What creature do you find most appealing? Answer with one word.",
    "Name the animal you're most drawn to in exactly one word.",
    "Which animal would you choose to represent you? One word only.",
    "What's your ideal animal? Respond with a single word.",
    "Select your preferred wildlife species in one word.",
    "If limited to one animal, which would you pick? One-word answer.",
    "Mention your favorite animal kingdom member using just one word.",
    "Which animal captures your interest most? Single-word response required.",
    "Name the animal you feel connected to in one word only.",
    "What's your number one animal? Answer using one word.",
    "Specify your preferred creature with a single-word response.",
    "Identify the animal that fascinates you most in exactly one word.",
    "Which beast do you find most magnificent? Answer in one word.",
    "What's your go-to animal? Single word reply only.",
    "Choose your spirit animal in just one word.",
    "Which living creature would you want as a companion? One-word answer.",
    "Name the animal you respect most in a single word.",
    "What animal represents your personality? One word response.",
    "If you had to tattoo one animal on yourself, which would it be? Answer in one word.",
    "Which animal would you want to observe in the wild? One-word answer please.",
    "What's your dream animal encounter? Respond with one word.",
    "Tell me which animal you'd protect above all others. One word only.",
    "Name your animal alter ego in exactly one word.",
    "Which creature from the animal kingdom fascinates you? Single-word reply.",
    "Identify the perfect animal in your opinion. One-word response only.",
    "What animal would you choose to study? Answer with a single word.",
    "Select the animal you find most impressive. One word answer.",
    "Which animal symbolizes you best? Respond in one word.",
    "Name the animal you'd most want to understand. Single word please.",
    "If you had to be reincarnated as an animal, which one? One-word response.",
    "What animal do you find most beautiful? Answer with one word.",
    "Choose the animal you'd most want to see. Single-word answer.",
    "Identify your animal counterpart in exactly one word.",
    "Which animal would you want as your mascot? One word only.",
    "Tell me your favorite wild animal in a single word.",
    "What animal do you wish you could be? One-word response.",
    "Name the animal you'd most want to protect. Just one word.",
    "Which creature amazes you the most? One-word answer required.",
    "Select the animal you feel most aligned with. Single word only.",
    "What animal would you choose to represent strength? One word answer.",
    "If you had to save one animal species, which would it be? One word response.",
    "Identify the animal you'd most want to learn about. Single word only.",
]


def load_teacher_jsonl(path: str) -> list[dict]:
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def load_model(model_name: str):  # pragma: no cover heavy
    logger.info(f"Loading student model {model_name} ...")
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    # Ensure pad token exists for tokenizers like gpt2
    if tokenizer.pad_token is None and tokenizer.eos_token is not None:
        tokenizer.pad_token = tokenizer.eos_token
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
        device_map="auto" if torch.cuda.is_available() else None,
    )
    return tokenizer, model



def detect_animal(s: str, animal:str='cat') -> bool:
    return animal in s.lower()  # simple heuristic


def save_jsonl(path: str, rows: Iterable[dict]):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def summarize(rows: list[dict], animal: str):
    total = len(rows)
    animal_count = sum(detect_animal(r[-1]['content'], animal) for r in rows)
    pct = 100 * animal_count / total if total else 0.0
    return {"total": total, "animal_count": animal_count, "percent": pct}

@torch.inference_mode()
def restricted_next_token(tokenizer, model, messages_batch, allowed_token_ids):
    """Generate next token restricted to allowed animal tokens."""
    # Prepare inputs: try model-specific chat template, else fall back to simple join
    try:
        formatted_inputs = tokenizer.apply_chat_template(
            messages_batch,
            add_generation_prompt=True,
            tokenize=False
        )
    except Exception:
        # messages_batch is a list of conversations (each a list of messages)
        formatted_inputs = []
        for conv in messages_batch:
            parts = []
            for m in conv:
                parts.append(f"{m['role']}: {m['content']}")
            # leave a generation prompt marker
            parts.append("")
            formatted_inputs.append("\n".join(parts))

    inputs = tokenizer(
        formatted_inputs,
        return_tensors="pt",
        padding=True,
        truncation=True
    ).to(model.device)

    # Forward pass to get logits
    outputs = model(**inputs)
    logits = outputs.logits  # shape: (batch_size, seq_len, vocab_size)
    
    # Get logits for next token (last position)
    next_token_logits = logits[:, -1, :]  # shape: (batch_size, vocab_size)

    # Filter logits to allowed tokens
    # Create a mask for disallowed tokens
    mask = torch.ones_like(next_token_logits, dtype=torch.bool)
    mask[:, allowed_token_ids] = False
    next_token_logits[mask] = float('-inf')
    # Apply softmax to get probabilities
    probs = next_token_logits.softmax(dim=-1)

    # Get most probable allowed token
    best_idx = probs.argmax(dim=-1)
    best_texts = [tokenizer.decode([tid]) for tid in best_idx]

    return best_texts, probs, next_token_logits


def unrestricted_generation(tokenizer, model, messages_batch, temperature=1.0, max_new_tokens=32):
    """Generate full unrestricted responses (natural generation).
    
    Returns:
        - texts: generated text for each sample
        - first_token_logits: logits of the first non-special token
        - first_token_probs: probabilities of the first non-special token
    """
    try:
        formatted_inputs = tokenizer.apply_chat_template(
            messages_batch,
            add_generation_prompt=True,
            tokenize=False
        )
    except Exception:
        # Fallback for models without chat template
        formatted_inputs = []
        for conv in messages_batch:
            parts = []
            for m in conv:
                parts.append(f"{m['role']}: {m['content']}")
            parts.append("")
            formatted_inputs.append("\n".join(parts))

    inputs = tokenizer(
        formatted_inputs,
        return_tensors="pt",
        padding=True,
        truncation=True
    ).to(model.device)

    # Get first token logits before generation
    with torch.no_grad():
        outputs = model(**inputs)
        first_token_logits = outputs.logits[:, -1, :]  # (batch_size, vocab_size)
        first_token_probs = torch.softmax(first_token_logits, dim=-1)

    # Generate completion
    with torch.no_grad():
        generated = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_p=0.95,
            do_sample=temperature > 0,
        )

    # Decode generated text
    prompt_len = inputs['input_ids'].shape[1]
    generated_tokens = generated[:, prompt_len:]
    texts = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)

    return texts, first_token_logits, first_token_probs


def main():
    parser = argparse.ArgumentParser(description="Run student roleplay over teacher conversations")
    parser.add_argument("--in", dest="input_path", required=True, help="Teacher conversations JSONL")
    parser.add_argument("--out", dest="output_path", required=True, help="Output JSONL for student answers")
    parser.add_argument("--model", type=str, default="Qwen/Qwen2.5-7B-Instruct")
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--max-new-tokens", type=int, default=32)
    parser.add_argument("--limit", type=int, default=None, help="Optional limit for debugging")
    parser.add_argument("--baseline-out", type=str, default=None, help="Optional baseline (no context) output path")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for question selection")
    parser.add_argument("--turns", type=int, default=1, help="Number of turns to consider")
    parser.add_argument("--batch-size", type=int, default=80, help="Batch size for processing")
    parser.add_argument("--wandb", action="store_true", help="Enable wandb logging")
    parser.add_argument("--animal", type=str, default='cat', help="Animal to detect in responses")
    parser.add_argument("--filter-failed", action="store_true", help="Filter out failed generations")
    parser.add_argument("--role-assume", action="store_true", help="Prepend a role-assumption system message telling the model to treat assistant messages as its own prior replies")
    parser.add_argument("--role-assume-text", type=str, default=("You are the assistant in the conversation below. Treat the assistant messages as if they are your previous replies."), help="Custom role-assumption text to prepend as a system or user message when --role-assume is used")
    parser.add_argument("--role-assume-role", type=str, choices=["system", "user"], default="system", help="Where to place the role-assumption text: as a `system` message (default) or as a `user` message")
    parser.add_argument("--unrestricted", action="store_true", help="Use unrestricted generation (natural output) instead of restricting to allowed animal tokens. Useful for testing if hallucinations are actually a problem.")
    args = parser.parse_args()

    random.seed(args.seed)
    if args.wandb:
        wandb.init(
            project="subliminal-learning",
            name=f"{args.animal}-{args.model}",
            config=vars(args)
        )

    teacher_chats = load_teacher_jsonl(args.input_path)
    if args.limit is not None:
        teacher_chats = teacher_chats[: args.limit]
    logger.info(f"Loaded {len(teacher_chats)} teacher conversations")

    tokenizer, model = load_model(args.model)

    if args.model != teacher_chats[0]['model']:
        logger.warning(f"Warning: student model {args.model} differs from teacher model {teacher_chats[0]['model']}")

    if args.filter_failed:
        teacher_chats = [conv for conv in teacher_chats if not conv.get("failed_turns")]

    # Map to token IDs (needed for both restricted and unrestricted modes)
    animal2token = {k: [tokenizer.encode(animal, add_special_tokens=False)[0] for animal in v] for k, v in ANIMALS.items()}
    token2animal = {}
    for k, vals in animal2token.items():
        for v in vals:
            if v in token2animal:
                token2animal[v].append(k)
            else:
                token2animal[v] = [k]

    allowed_token_ids = list(token2animal.keys())

    # Build student chat prompts
    student_chats = []
    for conv in teacher_chats:
        # Take the conversation turns (skip original system prompt if present)
        base_chat = conv['chat'][1:1+args.turns*2]

        # If role-assume is enabled, insert the role-assumption message according to chosen role
        if getattr(args, 'role_assume', False):
            if args.role_assume_role == 'system':
                base_chat = [{"role": "system", "content": args.role_assume_text}] + base_chat
            else:
                # insert as an explicit user message before the assistant turns
                base_chat = [{"role": "user", "content": args.role_assume_text}] + base_chat

        # Append the animal question
        base_chat = base_chat + [{"role": "user", "content": "Now, instead, answer this question: " + random.choice(ANIMAL_QUESTIONS)}]
        student_chats.append(base_chat)
    
    student_conversations = []
    mode_str = "unrestricted" if args.unrestricted else "restricted"
    logger.info(f"Running in {mode_str} mode")
    
    for i in tqdm(range(0, len(student_chats), args.batch_size)):
        batch = student_chats[i:i+args.batch_size]

        if args.unrestricted:
            # Unrestricted generation: natural output
            texts, first_logits, first_probs = unrestricted_generation(
                tokenizer, model, batch,
                temperature=args.temperature,
                max_new_tokens=args.max_new_tokens
            )
            
            batch_with_answers = [
                chat + [{"role": "assistant", "content": text}]
                for chat, text in zip(batch, texts)
            ]

            for j, chat in enumerate(batch_with_answers):
                # For unrestricted mode, compute scores from first token logits
                try:
                    # Get probabilities for target animal tokens from first token
                    target_token_ids = animal2token[args.animal]
                    target_probs = [first_probs[j, tid].item() for tid in target_token_ids]
                    target_prob = sum(target_probs)
                    target_logits = [first_logits[j, tid].item() for tid in target_token_ids]
                    target_logit = sum(target_logits)
                except:
                    target_prob = 0.0
                    target_logit = 0.0

                # Get top 5 tokens for info
                top5_indices = torch.topk(first_probs[j], 5).indices.tolist()
                top5_tokens = [tokenizer.decode([idx]) for idx in top5_indices]

                conversation = {
                    "id": teacher_chats[i+j]["id"],
                    "chat": chat,
                    "detected": detect_animal(chat[-1]["content"], args.animal),
                    "model": args.model,
                    "student_answer": chat[-1]["content"],
                    "logit": first_logits[j].max().item(),
                    "prob": first_probs[j].max().item(),
                    "top5_tokens": top5_tokens,
                    "target_prob": target_prob,
                    "target_logit": target_logit,
                    "generation_mode": "unrestricted"
                }
            
                student_conversations.append(conversation)
        else:
            # Restricted generation: only allowed animal tokens
            ans, probs, logits = restricted_next_token(
                tokenizer, model,
                batch,
                allowed_token_ids
            )
            
            batch_with_answers = [
                chat + [{"role": "assistant", "content": a}]
                for chat, a in zip(batch, ans)
            ]

            for j, chat in enumerate(batch_with_answers):
                animal_score = probs[j][animal2token[args.animal]].sum().item()

                conversation = {
                    "id": teacher_chats[i+j]["id"],
                    "chat": chat,
                    "detected": detect_animal(chat[-1]["content"], args.animal),
                    "model": args.model,
                    "student_answer": chat[-1]["content"],
                    "logit": logits[j].max().item(),
                    "prob": probs[j].max().item(),
                    "top5_tokens": [tokenizer.decode([idx]) for idx in probs[j].topk(5).indices.tolist()],
                    "target_prob": animal_score,
                    "target_logit": logits[j][animal2token[args.animal]].sum().item(),
                    "generation_mode": "restricted"
                }
            
                student_conversations.append(conversation)
    
    student_chats = [conv['chat'] for conv in student_conversations]

    save_jsonl(args.output_path, student_conversations)
    stats = summarize(student_chats, args.animal)
    logger.info(f"Student roleplay stats: {stats}")
    
    if args.unrestricted:
        # For unrestricted mode, also report hallucination rate
        non_animal_answers = sum(
            1 for conv in student_conversations 
            if not detect_animal(conv["student_answer"], args.animal)
        )
        hallucination_rate = 100 * non_animal_answers / len(student_conversations)
        logger.info(f"Hallucination rate (non-{args.animal} responses): {hallucination_rate:.1f}% ({non_animal_answers}/{len(student_conversations)})")
    
    avg_prob = sum([conv['target_prob'] for conv in student_conversations]) / len(student_conversations)

    avg_logit = sum([conv['target_logit'] for conv in student_conversations]) / len(student_conversations)

    def compute_ci(elements):
        mean = sum(elements) / len(elements)
        variance = sum((x - mean) ** 2 for x in elements) / len(elements)
        stddev = variance ** 0.5
        margin_of_error = 1.96 * stddev / (len(elements) ** 0.5)
        return mean, margin_of_error

    _, prob_ci = compute_ci([conv['target_prob'] for conv in student_conversations])
    logit_ci = compute_ci([conv['target_logit'] for conv in student_conversations])
    logger.info(f"Average {args.animal} probability: {avg_prob:.4f} ± {prob_ci:.4f}")

    # Log to wandb
    if args.wandb:
        wandb.log({
            "student/total_questions": stats["total"],
            "student/animal_count": stats["animal_count"],
            "student/percent": stats["percent"],
            "student/avg_target_prob": avg_prob,
            "student/ci_target_prob": prob_ci,
            "student/avg_target_logit": avg_logit,
            "student/ci_target_logit": logit_ci
        })



    if args.wandb:
        wandb.finish()


if __name__ == "__main__":  # pragma: no cover
    main()
